version: '3.9'
services:
  gateway:
    image: tonysoprano228/kittygram_gateway
    container_name: kittygram_gateway
    volumes:
      - ./static:/backend/static
      - ./media:/backend/media  
    ports:
      - 80:80
    networks:
      - appBridge

  backend:
    image: tonysoprano228/kittygram_backend
    container_name: kittygram_backend
    environment:
     - DB_HOST=${DB_HOST}
     - DB_PORT=${DB_PORT}
     - DB_NAME=${DB_NAME}
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./static:static
      - ./media:media 
    ports:
      - 8000:8000
    networks:
      - appBridge

  frontend:
    image: tonysoprano228/kittygram_frontend
    container_name: kittygram_frontend
    volumes:
      - ./static:/app/static     
    ports:
      - 8001:8000
    networks:
      - appBridge

  postgres:
    image: postgres:13
    container_name: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - appBridge

volumes:
  static:
    driver: local
  media:
    driver: local
  pg_data:
    driver: local

networks:
  appBridge:
    driver: bridge 