version: '3.9'
services:
  
  db:
    image: postgres:13.10
    container_name: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-bridge
  backend:
    image: tonysoprano228/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
    networks:
      - app-bridge
  frontend:
    env_file: .env
    image: tonysoprano228/kittygram_frontend:latest
    #command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    networks:
      - app-bridge
  gateway:
    image: tonysoprano228/kittygram_gateway:latest
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/app/media/
    networks:
      - app-bridge

volumes:
  static:
  media:
  pg_data:

networks:
  app-bridge:
    driver: bridge