on:
  push:
    branches:
      - main


jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update pip
      run: python3 -m pip install --upgrade pip

    - name: Install dependencies
      run: |
           cd backend && pip install -r requirements.txt
           
    - name: Install pep8  
      run: pip install pycodestyle

    - name: Run pep8
      run: |
           cd backend && pycodestyle .
      continue-on-error: true

    - name: Install pytest
      run: pip install pytest

    - name: Run tests
      run:  cd backend && pytest ../tests
      continue-on-error: true
  
  push_to_registry:
    name: Push Docker image to Docker Hub
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin  

      - name: Build and push backend image
        run: |
            cd backend
            docker build . -t tonysoprano228/kittygram_backend
            docker push tonysoprano228/kittygram_backend

      - name: Build and push frontend image
        run: |
            cd frontend
            docker build . -t tonysoprano228/kittygram_frontend
            docker push tonysoprano228/kittygram_frontend

      - name: Build and push nginx image
        run: |
            cd nginx
            docker build . -t tonysoprano228/kittygram_gateway
            docker push tonysoprano228/kittygram_gateway